use_frameworks!


platform :ios, '11.0'

target 'Validatr_Example' do
  pod 'Validatr', :path => '../'

  target 'Validatr_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end

